# Generated by Django 3.2.5 on 2021-07-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='miniSuperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paternal_surname', models.CharField(max_length=50)),
                ('maternal_surname', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=2, max_digits=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.DecimalField(decimal_places=10, max_digits=10, unique=True)),
            ],
        ),
    ]
